### ISSUE TITLE
Bug: Dead snakes are displayed in env.render()

### ISSUE THREAD

**Issue by MNThomson** [DaBultz/pz-battlesnake#10]
Running `test.py`:
<details>
  <summary>Test,py</summary>

  ```python
from pz_battlesnake.env import standard_v0

env = standard_v0.env()

for _ in range(1):
    env.reset()
    done = False
    alive_agents = env.agents.copy()

    while not done:
        env.render()

        for agent in alive_agents:

            obs, rewards, _done, info = env.last()

            if _done:
                env.step(None)
                alive_agents.remove(agent)
                continue

            action = "up"
            env.step(action)

        if len(alive_agents) <= 1:
            done = True
  ```
  
</details>

Clearly in the example below, `agent_3` should not be printed from turn 2 onward. The expected behaviour (like in the official `rules` cli) is that dead snakes are not displayed. The dead snake if not still in the json api object luckily, so this shouldn't be extremely hard to fix. 

```
docker run -v $(pwd):/project/pz-battlesnake  dabultz/pz_battlesnake python /project/pz-battlesnake/example/test.py
2022/06/26 21:01:07 Ruleset: standard, Seed: 1656277267676684699, Turn: 0
Hazards ░: []
Food ⚕: [{0 4} {6 0} {10 6} {6 10} {5 5}]
agent_0 ■: {agent_0 [{1 5} {1 5} {1 5}] 100  0 }
agent_1 ⌀: {agent_1 [{5 1} {5 1} {5 1}] 100  0 }
agent_2 ●: {agent_2 [{9 5} {9 5} {9 5}] 100  0 }
agent_3 ☻: {agent_3 [{5 9} {5 9} {5 9}] 100  0 }
◦◦◦◦◦◦⚕◦◦◦◦
◦◦◦◦◦☻◦◦◦◦◦
◦◦◦◦◦◦◦◦◦◦◦
◦◦◦◦◦◦◦◦◦◦◦
◦◦◦◦◦◦◦◦◦◦⚕
◦■◦◦◦⚕◦◦◦●◦
⚕◦◦◦◦◦◦◦◦◦◦
◦◦◦◦◦◦◦◦◦◦◦
◦◦◦◦◦◦◦◦◦◦◦
◦◦◦◦◦⌀◦◦◦◦◦
◦◦◦◦◦◦⚕◦◦◦◦
2022/06/26 21:01:07 Ruleset: standard, Seed: 1656277267676684699, Turn: 1
Hazards ░: []
Food ⚕: [{0 4} {6 0} {10 6} {6 10} {5 5} {7 10}]
agent_0 ■: {agent_0 [{1 6} {1 5} {1 5}] 99  0 }
agent_1 ⌀: {agent_1 [{5 2} {5 1} {5 1}] 99  0 }
agent_2 ●: {agent_2 [{9 6} {9 5} {9 5}] 99  0 }
agent_3 ☻: {agent_3 [{5 10} {5 9} {5 9}] 99  0 }
◦◦◦◦◦☻⚕⚕◦◦◦
◦◦◦◦◦☻◦◦◦◦◦
◦◦◦◦◦◦◦◦◦◦◦
◦◦◦◦◦◦◦◦◦◦◦
◦■◦◦◦◦◦◦◦●⚕
◦■◦◦◦⚕◦◦◦●◦
⚕◦◦◦◦◦◦◦◦◦◦
◦◦◦◦◦◦◦◦◦◦◦
◦◦◦◦◦⌀◦◦◦◦◦
◦◦◦◦◦⌀◦◦◦◦◦
◦◦◦◦◦◦⚕◦◦◦◦
2022/06/26 21:01:07 Ruleset: standard, Seed: 1656277267676684699, Turn: 2
Hazards ░: []
Food ⚕: [{0 4} {6 0} {10 6} {6 10} {5 5} {7 10}]
agent_0 ■: {agent_0 [{1 7} {1 6} {1 5}] 98  0 }
agent_1 ⌀: {agent_1 [{5 3} {5 2} {5 1}] 98  0 }
agent_2 ●: {agent_2 [{9 7} {9 6} {9 5}] 98  0 }
agent_3 ☻: {agent_3 [{5 11} {5 10} {5 9}] 98 wall-collision 0 }
◦◦◦◦◦☻⚕⚕◦◦◦
◦◦◦◦◦☻◦◦◦◦◦
◦◦◦◦◦◦◦◦◦◦◦
◦■◦◦◦◦◦◦◦●◦
◦■◦◦◦◦◦◦◦●⚕
◦■◦◦◦⚕◦◦◦●◦
⚕◦◦◦◦◦◦◦◦◦◦
◦◦◦◦◦⌀◦◦◦◦◦
◦◦◦◦◦⌀◦◦◦◦◦
◦◦◦◦◦⌀◦◦◦◦◦
◦◦◦◦◦◦⚕◦◦◦◦
2022/06/26 21:01:07 Ruleset: standard, Seed: 1656277267676684699, Turn: 3
Hazards ░: []
Food ⚕: [{0 4} {6 0} {10 6} {6 10} {5 5} {7 10}]
agent_0 ■: {agent_0 [{1 8} {1 7} {1 6}] 97  0 }
agent_1 ⌀: {agent_1 [{5 4} {5 3} {5 2}] 97  0 }
agent_2 ●: {agent_2 [{9 8} {9 7} {9 6}] 97  0 }
agent_3 ☻: {agent_3 [{5 11} {5 10} {5 9}] 98 wall-collision 0 }
◦◦◦◦◦☻⚕⚕◦◦◦
◦◦◦◦◦☻◦◦◦◦◦
◦■◦◦◦◦◦◦◦●◦
◦■◦◦◦◦◦◦◦●◦
◦■◦◦◦◦◦◦◦●⚕
◦◦◦◦◦⚕◦◦◦◦◦
⚕◦◦◦◦⌀◦◦◦◦◦
◦◦◦◦◦⌀◦◦◦◦◦
◦◦◦◦◦⌀◦◦◦◦◦
◦◦◦◦◦◦◦◦◦◦◦
◦◦◦◦◦◦⚕◦◦◦◦
```
The `printMap()` & `render()` functions are extremely similar so it might be a good idea to simply call `printMap()` from pz-battlesnake instead of re-implementing it. The `useColor` option should be passed through in the `gamestate` instead of function arguments.

**Comment by DaBultz** [comment]
Gonna get a fix together,

> The printMap() & render() functions are extremely similar so it might be a good idea to simply call printMap() from pz-battlesnake instead of re-implementing it

Are you talking about the render() in the GO or Python part?

**Comment by MNThomson** [comment]
> Are you talking about the render() in the GO or Python part?

Curious why you aren't just calling the `printMap` function that already exists in the official battlesnake rules repo. Seems easier than reimplementing

**Comment by DaBultz** [comment]
> Curious why you aren't just calling the printMap function that already exists in the official battlesnake rules repo. Seems easier than reimplementing

to call the PrintMap in the official one, I would need to instantiate their GameState and keep the state synced, A bit more complicated than re-implementing it. 

My plan in the future to look at the rendering, right now my focus is on #8 and next one would be #5, I have planned to look at rendering (will be done at the same time as vectorized environment)
