### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by mightyiam** [DaBultz/pz-battlesnake#20]
Hi, @DaBultz . Sorry for contacting you here. I couldn't find your contact details anywhere. I saw [a deprecated package of yours](https://www.npmjs.com/package/eslint-config-love) on npm and I was wondering whether you might consider gifting it to me. I'd like to [rename](https://github.com/mightyiam/eslint-config-love/pull/1462) a project of mine and I like that name. If you could consider, all my contact details are in my profile. Thank you.

**Comment by DaBultz** [comment]
Hey, no worries. I wouldn't mind gifting it to you :) do you want me to delete my old package or invite you then remove myself, so you become the owner?

**Comment by mightyiam** [comment]
Oh, that's wonderful. The second option, please.

**Comment by DaBultz** [comment]
@mightyiam I've sent an invitation, when you've accepted it. I will remove myself.

**Comment by mightyiam** [comment]
Accepted!

**Comment by DaBultz** [comment]
Alright, I've removed myself, so you should now own the package :)

**Comment by mightyiam** [comment]
Seems like it. You are the best. Thank you, @DaBultz!
